#
# Copyright (c) 2018 Oracle and/or its affiliates. All rights reserved
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

apiVersion: v1
kind: Service
metadata:
  name: oke-sample
  labels:
    app: oke-sample
spec:
  ports:
  - port: 8080
  selector:
    app: oke-sample
    tier: frontend
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oke-sample
  labels:
    app: oke-sample
spec:
  selector:
    matchLabels:
      app: oke-sample
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: oke-sample
        tier: frontend
    spec:
      containers:
      - name: oke-sample
        image: iad.ocir.io/idsufmye3lml/wonjo/sample-app:${BUILD_NUMBER}
        env:
        - name: BUILD_NUMBER 
          value: "0"
        - name: MYSQL_SERVICE_HOST
          value: mysql
        - name: MYSQL_SERVICE_USER
          value: "test"
        - name: MYSQL_SERVICE_PASSWORD
          value: "Welcome1"
        - name: MYSQL_SERVICE_DATABASE
          value: "sample"
        ports:
        - containerPort: 8080
          name: oke-sample
      imagePullSecrets:
      - name: ocirsecret 
---
